/*
 * Generated by Bluespec Compiler, version 2023.01-23-g764b7230 (build 764b7230)
 * 
 * On Tue Sep 12 11:38:22 IST 2023
 * 
 */

/* Generation options: */
#ifndef __mkPipe_h__
#define __mkPipe_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkPipe module */
class MOD_mkPipe : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_x1;
  MOD_Reg<tUInt32> INST_x2;
  MOD_Reg<tUInt32> INST_x3;
  MOD_Reg<tUInt32> INST_x4;
 
 /* Constructor */
 public:
  MOD_mkPipe(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt32 DEF_b__h249;
  tUInt32 DEF_b__h232;
  tUInt32 DEF_b__h182;
  tUInt32 DEF_b__h219;
 
 /* Rules */
 public:
  void RL_r1();
  void RL_show();
 
 /* Methods */
 public:
  void METH__write(tUInt32 ARG__write_1);
  tUInt8 METH_RDY__write();
  tUInt32 METH__read();
  tUInt8 METH_RDY__read();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkPipe &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkPipe &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkPipe &backing);
};

#endif /* ifndef __mkPipe_h__ */
