//
// Generated by Bluespec Compiler, version 2023.01-23-g764b7230 (build 764b7230)
//
// On Fri Aug 18 12:32:19 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// the_answer                     O    32 const
// RDY_the_answer                 O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// the_answer_a                   I    32 unused
// the_answer_b                   I    32 unused
// the_answer_cin                 I    32 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module full_add(CLK,
		RST_N,

		the_answer_a,
		the_answer_b,
		the_answer_cin,
		the_answer,
		RDY_the_answer);
  input  CLK;
  input  RST_N;

  // value method the_answer
  input  [31 : 0] the_answer_a;
  input  [31 : 0] the_answer_b;
  input  [31 : 0] the_answer_cin;
  output [31 : 0] the_answer;
  output RDY_the_answer;

  // signals for module outputs
  wire [31 : 0] the_answer;
  wire RDY_the_answer;

  // value method the_answer
  assign the_answer = 32'hAAAAAAAA ;
  assign RDY_the_answer = 1'd1 ;
endmodule  // full_add

